### ISSUE TITLE
Edit Users page results in 500 Error

### ISSUE THREAD

**Issue by klou** [klou/stuff_to_do_plugin#1]
```
  Rendered plugins/stuff_to_do_plugin/app/views/account_settings/_stuff_to_do_account_settings.html.erb (8.5ms)
  Rendered my/account.html.erb within layouts/base (55.2ms)
Completed 500 Internal Server Error in 110ms (ActiveRecord: 9.7ms)

ActionView::Template::Error (undefined method `stuff_to_do_view_all_reportees' for #<UserPreference:0x0000000a4d6d18>):
     6:                         <%= labelled_fields_for :pref, @user.pref do |pref_fields| %>
     7:                                 <p><%= pref_fields.check_box :stuff_to_do_enabled %></p>
     8:                                 <% if @user.allowed_to?(:manage_stuff_to_do_reportees, @project, :global => true) %>
     9:                                         <p><%= pref_fields.check_box :stuff_to_do_view_all_reportees %></p>
    10:                                         <% if !@user.pref[:stuff_to_do_view_all_reportees] %>
    11:                                                 <%= link_to l(:stuff_to_do_manage_reportees), { :controller => 'stuff_to_do_reportee', :action => 'index', :user_id => @user.id } %>
    12:                                         <% end %>
  lib/redmine/views/labelled_form_builder.rb:34:in `check_box'
  app/helpers/application_helper.rb:1037:in `labelled_fields_for'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/my/account.html.erb:34:in `block in _app_views_my_account_html_erb__2381465509972137883_87002660'
  app/helpers/application_helper.rb:1030:in `labelled_form_for'
  app/views/my/account.html.erb:14:in `_app_views_my_account_html_erb__2381465509972137883_87002660'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I think this is tied to the above function, which ONLY affects Users who are Project Managers.

**Comment by klou** [comment]
Due to changing forks, I guess I had a different db migration as user_preferences.stuff_to_do_view_all_reportees did not exist.

Deleted the migrations from schema_migrations, re-ran the plugin migration, and it successfully updated.
